### ISSUE TITLE
[TuyaIR] Failed to change AC status due to error permission deny

### ISSUE THREAD

**Issue by capiotti** [prasad-edlabadka/homebridge-tuya-ir#10]
I realize this may not be an issue but maybe someone can point out something I missed.
Created an account on IoT Platform, linked my SmartLife app account, used the IoT Platform credentials and both IR device ID and AirCon Device ID. On homebridge I get signing in successful, it finds and lists my aircon but I keep getting [TuyaIR] Failed to change AC status due to error permission deny

**Comment by prasad-edlabadka** [comment]
You will need to authorise your project to use IR APIs. Please refer readme.md

**Comment by capiotti** [comment]
My device is in my project which is authorized on the subscribed service. That is the odd reason I didn't understand why it keeps talking about permission deny, I'll try to find out what is going on...

**Comment by prasad-edlabadka** [comment]
You need to authorise some more services. I have updated readme to reflect these.
