### ISSUE TITLE
False Current Temperature

### ISSUE THREAD

**Issue by sayam93** [prasad-edlabadka/homebridge-tuya-ir#103]
My air conditioner controlled by Tuya Smart IR device exposes the a/c target temperature as a current temperature sensor when on and last used target temperature when off in homekit with this plugin. Is there a way to hide this sensor reading i.e. completely hide the current temperature being exposed by the plugin to Homekit? A way to hide unwanted modes and characteristics like current temperature would really be appreciated since the smart IR seems to think my AC has a heat mode when it does not!

**Comment by prasad-edlabadka** [comment]
I didn't understand the issue. Can you please elaborate?

**Comment by Hyperspeed00** [comment]
I have this issue also where there are two temperatures exposed by my IR AC Device. one is the current room temp and the other is the target room temp. However the issue is with the current room temp being always equal to the target temp. these two temps should be different than each other unless the target temp is reached

**Comment by prasad-edlabadka** [comment]
Tuya APIs don't provide two different temperatures. Their status API provides information about wind, mode, power and temperature. The temperate is the current temperature as displayed on the AC unit. So, there is no way to distinguish between the two.

**Comment by Hyperspeed00** [comment]
<img width="588" alt="AC Homebridge" src="https://github.com/user-attachments/assets/1f5ae91f-d9db-4874-8eaa-6ac302da6d7f">

disabling one of these temperatures

**Comment by Hyperspeed00** [comment]
<img width="335" alt="ha ac" src="https://github.com/user-attachments/assets/0352ca0a-d0bc-473b-8540-322ea3473c15">

This is what I was able to expose using localtuya

**Comment by sayam93** [comment]
I meant to ask if there was a way to not expose the temp as highlighted in the red box in the screenshot.
<img width="295" alt="Screenshot 2024-08-19 at 2 03 02 AM" src="https://github.com/user-attachments/assets/857c0257-9e9c-4909-978f-111229344ac6">

**Comment by Hyperspeed00** [comment]
by using this HACS module in HA https://github.com/jcwillox/hass-template-climate you can feed it the information you want to expose. in addition you can set it up to only show the supported heat/cool modes that you unit supported.

```
climate:
  - platform: climate_template
    name: Living Room Aircon
    modes:            // supported modes by your Unit (should be the same as mine only supports cool also)
      - "off"
      - "cool"
    min_temp: 17         // min and max target temps supported by your unit mine goes from 17 to 30 
    max_temp: 30
    current_temperature_template: "{{ states('sensor.current_temp') }}"            // get current temp from localtuya or any other device in HA (can be removed if there is no device to take info from)
    precision: 0.1              // correct the value of the current temp (should be removed if current temp is not needed or value is not in XXX format (234 to 23.4))
    current_humidity_template: "{{ states('sensor.room_humidity') }}"                 // get current humidity from localtuya or any other device in HA (can be removed if there is no device to take info from)
    target_temperature_template: "{{ states('number.target_temp') }}"                 // get target temp from localtuya or any other device in HA (can be removed if there is no device to take info from)
    hvac_mode_template: "{{ states('select.mode') }}"                 // get current mode from localtuya or any other device in HA (can be removed if there is no device to take info from)
    set_temperature:         // to control target temp from the climate template
    - service: climate.set_temperature              // using HA built in climate service
      data:
        entity_id: climate.aircon            // entity id for homebridge AC
        temperature: "{{ temperature }}"
    set_hvac_mode:                 // to control mode from the climate template
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.aircon                  // entity id for homebridge AC
          hvac_mode: "{{ hvac_mode }}"
```

this is my current setup with it. you can just remove the current temp/current humidity from the config and change where the climate template takes its info from (my config points to localtuya entities to always have homekit be in sync with tuya) or remove it so only it gets updated by HA/Homekit (changes made in tuya will not reflect but changes in HA/Homekit will reflect in tuya). then by changing the set temperature and set hvac mode entity id to the homebridge Aircon entity id it should work for you. then just expose template climate entity to Homekit.  by doing this you will get two entities in HA but one in homekit with the correct info like this

![Aircon](https://github.com/user-attachments/assets/64766cda-40b8-41d1-92c0-352cdacb6e23)

then you can set the homebridge entity to be hidden from HA

**Comment by Hyperspeed00** [comment]
just tested it out this is the climate entity that i got without relying on localtuya

![image](https://github.com/user-attachments/assets/fabcaa11-59c2-4471-a065-c8e502690fa2)

this is what i got in HA but it is still sending a current temp to homekit. So it would not work for your case unless you add in a temp sensor

![WhatsApp Image 2024-08-19 at 3 41 40 AM](https://github.com/user-attachments/assets/6cf8e447-64f8-4356-a52c-83f1e8f9a3ca)

The one on the left is using the external sensor (built into tuya IR hub) one on the right is the one that does not have a temp sensor in HA

So its either an issue with HA homekit bridge or Homekit doesn't support climate without temp sensors

**Comment by sayam93** [comment]
Thanks! This looks like it would be perfect for my use case. Could you kindly post the config for the sensor on the left where the entity is grabbing the value from an external sensor?

Also, I assume that climate.aircon is the original tuya entity?

**Comment by Hyperspeed00** [comment]
climate.aircon is the tuya entity id yes. my external sensor entity id is sensor.current_temp which was setup using localtuya but it could differ depending on its integration. so you could use "" current_temperature_template: "{{ states('replace with you sensor entity id') }}" "" in the config. you can get the entity id from the device setting in HA after setting the device up

**Comment by sayam93** [comment]
Thanks! I will test this out right away! 😀
