### ISSUE TITLE
ERROR Client ID is not configured.

### ISSUE THREAD

**Issue by freemanuk** [prasad-edlabadka/homebridge-tuya-ir#106]
I am not sure what went wrong and I keep getting an error saying my Client ID is not configured (see below). I have been using my Client ID for other Tuya plugins all this while and there are no problems.

07/07/2024, 16:38:10Tuya Ir BridgeLoaded plugin 'homebridge-tuya-ir'
07/07/2024, 16:38:10Tuya Ir BridgeLoading 1 platforms...
07/07/2024, 16:38:10Tuya Ir BridgeTuyaIRERRORClient ID is not configured. Please check your config.json
07/07/2024, 16:38:11Tuya Ir BridgeBridge is running on port 51936.

**Comment by prasad-edlabadka** [comment]
This looks like missing config. Can you please check config.json is correctly configured? Please refer to Readme or use Homebridge UI to configure.

**Comment by freemanuk** [comment]
Have done a check with jasonformatter and it is valid.

{
    "platform": "TuyaIR",
    "name": "TuyaIR",
    "client_id": "aaaaaaaa",
    "region": "eu",
    "secret": "bbbbbbbb",
    "smartIR": [
        {
            "deviceId": "ccccccccccccc",
            "autoFetchRemotes": true,
            "devices": [
                {
                    "id": "ddddddddddddd"
                }
            ]
        }
    ]
}

**Comment by prasad-edlabadka** [comment]
The configuration is incorrect. Please refer to readme. The sample configuration should be like the one below.
```
"platforms": [
    {
        "name": "TuyaIR",
        "tuyaAPIClientId": "Your Tuya Client ID",
        "tuyaAPISecret": "Your Tuya API Secret",
        "deviceRegion": "eu",
        "smartIR": [
            {
                "deviceId": "xxxxxxx",
                "autoFetchRemotesFromServer": false,
                "configuredRemotes": [
                    {
                        "id": "xxxxxxx",
                        "diy": false,
                        "model": "Sample",
                        "brand": "Sample Brand"
                    },
                    {
                        "id": "xxxxxx",
                        "diy": false,
                        "model": "Sample",
                        "brand": "Sample Brand"
                    }
                ]
            }
        ],
        "platform": "TuyaIR"
    }
]
```
