### ISSUE TITLE
Just a question from a confused guy.

### ISSUE THREAD

**Issue by victorczon** [prasad-edlabadka/homebridge-tuya-ir#13]
In Tuya smart life app I have added universal remote control and have got a ID for the blaster. But because my ceiling fan is not a known device I needed to use the DIY function and add all "actions" manually . So in this DIY group that also have a different ID I have added so I can control three different speeds and turn it off. 4 in total.  I guess all "actions" in that group have different id's, but I have not been able to find it. Is it even possible for the plugin and tuya api to detect all id's in that diy group? I have been looking in device logs when I have turned the fan on and off   and it shows some string of text  but I have no clue what it means or if I can use it somehow. This is making me so confused. Sorry my english is not that great so not sure if what I write is readable.

This is the string of text from the device log
`{\"control\":\"send_ir\",\"head\":\"\",\"key1\":\"1LQV3AfsEqQHCAckE2wHJBMIB4gQUBXcB2wHJBMIB4gTCAckE2wHJBBQFkAEUBdUbLQWQARQFdwHbAckEwgHiBMIByQQUBZABwgHiBMIByQTCAeIEwgHiBBQFdwEUBdUbLQWQARQFkAGpAfsEwgHJBKkB+wQUBZABwgHJBMIB4gTCAckE2wHJBPsEqQEUBdUbLQV3AS0FXgH0AbAE2wHJBNsBsAQtBXcB2wHJBNsBsAT0AbAE2wGwBEYFXgEtBdUbRgVeAS0FdwHbAbAE9AGwBPQBsAQtBV4B9AGwBNsByQTbAbAE9AGwBC0FdwEtBdUbLQV3AS0FXgH0AbAE2wHJBNsBsAQtBXcB2wHJBNsBsATCAeIEwgHiBPsEkAEUBSAc4gSpAfsEqQGpAfsEkAH7BKkB+wTiBMIBkAH7BKkB+wSpAfsEkAH7BPsEqQHJBDkcyQTbAckE2wF3ARQFkAEUBXcBLQXJBMIBkAEUBXcBLQV3AS0FdwEtBbAE9AGwBFIcsATbAckE2wF3AS0FXgEtBXcBLQWwBPQBXgEtBXcBLQV3AS0FXgEtBckE2wGwBFIcyQTbAbAE9AFeAS0FdwEtBV4BRgWwBPQBXgFGBUUBXwVFAUYFXgFGBZcEDQKXBGsclwQNApcE9AFeAV8FLAF4BSwBXwV+BCYCLAF4BSwBXwUsAXgFEwGRBWUEPwJMBOgcMwRYAjMEigLIAPUFlgAOBpYAwNQ=\",\"type\":0,\"delay\":300}"{"201":"{\"control\":\"send_ir\",\"head\":\"\",\"key1\":\"1LQV3AfsEqQHCAckE2wHJBMIB4gQUBXcB2wHJBMIB4gTCAckE2wHJBBQFkAEUBdUbLQWQARQFdwHbAckEwgHiBMIByQQUBZABwgHiBMIByQTCAeIEwgHiBBQFdwEUBdUbLQWQARQFkAGpAfsEwgHJBKkB+wQUBZABwgHJBMIB4gTCAckE2wHJBPsEqQEUBdUbLQV3AS0FXgH0AbAE2wHJBNsBsAQtBXcB2wHJBNsBsAT0AbAE2wGwBEYFXgEtBdUbRgVeAS0FdwHbAbAE9AGwBPQBsAQtBV4B9AGwBNsByQTbAbAE9AGwBC0FdwEtBdUbLQV3AS0FXgH0AbAE2wHJBNsBsAQtBXcB2wHJBNsBsATCAeIEwgHiBPsEkAEUBSAc4gSpAfsEqQGpAfsEkAH7BKkB+wTiBMIBkAH7BKkB+wSpAfsEkAH7BPsEqQHJBDkcyQTbAckE2wF3ARQFkAEUBXcBLQXJBMIBkAEUBXcBLQV3AS0FdwEtBbAE9AGwBFIcsATbAckE2wF3AS0FXgEtBXcBLQWwBPQBXgEtBXcBLQV3AS0FXgEtBckE2wGwBFIcyQTbAbAE9AFeAS0FdwEtBV4BRgWwBPQBXgFGBUUBXwVFAUYFXgFGBZcEDQKXBGsclwQNApcE9AFeAV8FLAF4BSwBXwV+BCYCLAF4BSwBXwUsAXgFEwGRBWUEPwJMBOgcMwRYAjMEigLIAPUFlgAOBpYAwNQ=\",\"type\":0,\"delay\":300}"}"201":"{\"control\":\"send_ir\",\"head\":\"\",\"key1\":\"1LQV3AfsEqQHCAckE2wHJBMIB4gQUBXcB2wHJBMIB4gTCAckE2wHJBBQFkAEUBdUbLQWQARQFdwHbAckEwgHiBMIByQQUBZABwgHiBMIByQTCAeIEwgHiBBQFdwEUBdUbLQWQARQFkAGpAfsEwgHJBKkB+wQUBZABwgHJBMIB4gTCAckE2wHJBPsEqQEUBdUbLQV3AS0FXgH0AbAE2wHJBNsBsAQtBXcB2wHJBNsBsAT0AbAE2wGwBEYFXgEtBdUbRgVeAS0FdwHbAbAE9AGwBPQBsAQtBV4B9AGwBNsByQTbAbAE9AGwBC0FdwEtBdUbLQV3AS0FXgH0AbAE2wHJBNsBsAQtBXcB2wHJBNsBsATCAeIEwgHiBPsEkAEUBSAc4gSpAfsEqQGpAfsEkAH7BKkB+wTiBMIBkAH7BKkB+wSpAfsEkAH7BPsEqQHJBDkcyQTbAckE2wF3ARQFkAEUBXcBLQXJBMIBkAEUBXcBLQV3AS0FdwEtBbAE9AGwBFIcsATbAckE2wF3AS0FXgEtBXcBLQWwBPQBXgEtBXcBLQV3AS0FXgEtBckE2wGwBFIcyQTbAbAE9AFeAS0FdwEtBV4BRgWwBPQBXgFGBUUBXwVFAUYFXgFGBZcEDQKXBGsclwQNApcE9AFeAV8FLAF4BSwBXwV+BCYCLAF4BSwBXwUsAXgFEwGRBWUEPwJMBOgcMwRYAjMEigLIAPUFlgAOBpYAwNQ=\",\"type\":0,\"delay\":300}"`

**Comment by madtempest** [comment]
I'm not the author, but at this point in time if your product is a DIY, it won't work with this plugin. Tuya has some default definitions for objects (TV, Fan, Air Conditioner etc) that the plugin author is directly translating from in order to make this work.

I wouldn't say its not possible, but DIY is going to be a significant amount of effort compared to the known types of objects to make them work.

**Comment by victorczon** [comment]
Yeah. I noticed that the DIY function is not the best way to do it. I have now also tried choosing the fan object/class but my model is not supported. So I manually tried to program the buttons. So now the buttons have a more normal string like "PowerOn" "PowerOff" "speed" etc, but I still can't get it to work. I will give up for now. I need to find another IR blaster that does not use Tuya.

**Comment by prasad-edlabadka** [comment]
I don’t think Tuya supports DIY using API. But will try to explore more.

**Comment by victorczon** [comment]
I still have no luck. When when using diy this is what I can see in the logs when I for example turn the light on. 
`\"send_ir\",\"head\":\"\",\"key1\":\"1LQVeAS0FdwHbAckE2wHJBMIB4gTCAckE2wHJBMIB4gQUBV4B9AHJBMIByQTbAScfLQVeAUYFXgHbAeIEwgHJBNsByQTbAckEwgHJBNsByQQUBXcB2wHJBNsByQTCAScfLQV3AS0FdwHbAckE2wHJBMIB4gTCAckE2wHJBMIB4gQUBV4B9AHJBMIB4gTCAScfLQVeAUYFXgHbAeIEwgHiBMIBsATbAckE2wGwBPQBsAQtBXcB2wGwBPQBsATbAScfLQV3AS0FXgH0AbAE9AGwBNsBsAT0AbAE9AGwBNsBsARGBV4B9AGwBNsBsAT0AScfLQVeAUYFXgHbAckE2wGwBPQBsATbAckE2wGwBNsByQQtBXcB2wGwBNsByQTCAUAfFAWQARQFqQGQAfsEqQH7BKkB4gSpAfsEqQH7BKkB4gT7BKkBqQH7BKkB4gSpAXIf4gSpAfsEqQGQARQFdwEUBZABFAWQARQFdwEUBZABFAXJBNsBdwEUBZABFAV3AaQfyQTbAbAE9AFeAS0FdwEtBV4BRgVeAS0FdwEtBV4BRgWwBNsBdwEtBV4BRgVeAaQfsAT0AbAE2wF3AS0FXgFGBV4BLQV3AS0FXgFGBV4BLQWwBPQBXgFGBV4BRgVeAaQfsAT0AZcEDQJFAUYFXgFGBUUBXwVFAUYFXgFGBUUBeAV+BA0CRQFfBSwBeAUTAQggTARYAkwEPwITAaoF4QDDBeEAwwXIANwFyAD1BZYApAaWAMDU\",\"type\":0,\"delay\":300}"` But I have no clue or even if I could use it somehow.

**Comment by victorczon** [comment]
It looks like it uses the same string of text every time when for example turning the light on. It's always the same. 
How does this plugin talk to tuya? does it sending commands like "PowerOn" "PowerOff" or does it send any else?

**Comment by prasad-edlabadka** [comment]
Ok..found the API. Will take a few days to add support for DIY remotes. For now it will work for AC and Fans only.

**Comment by prasad-edlabadka** [comment]
Added support for DIY fans. Please check. If it works, I will look to add AC support as well. But I haven't seen DIY AC requirement so far as Tuya has most of the brands configured.
