### ISSUE TITLE
Bug: AC Mode Not Set Correctly

### ISSUE THREAD

**Issue by mgrosman** [prasad-edlabadka/homebridge-tuya-ir#15]
I was able to get my AC added successfully to homebridge with this plugin. The temperature is adjusted correctly. However when I try to change the mode from the Home app (auto, cooling, heating, etc), the mode does not seem to change correctly. I hear beeps from the AC but the indicator light does not change according to the mode. Perhaps the correct code isn't passed?

**Comment by prasad-edlabadka** [comment]
Please note HomeKit only supports Heat and Cool mode. I have used "OFF" to set mode to "Auto". You can always switch AC off by using normal power command.
