### ISSUE TITLE
Now temp shows 0.0

### ISSUE THREAD

**Issue by ami9620** [prasad-edlabadka/homebridge-tuya-ir#16]
The current temp shows always 0.0
How to fix this?

**Comment by ami9620** [comment]
![FFF74D5C-CD92-4AD9-BB8F-AE153AAD8B82](https://user-images.githubusercontent.com/85903449/132800155-16e22b2e-438a-46e2-8b89-2ea5010a5188.png)

**Comment by prasad-edlabadka** [comment]
There isn’t a way to retrieve temperature from AC using IR. IR is one way communication only. So, temperature reading will not be reliable.

**Comment by ami9620** [comment]
Can you show the temp from the ir ?

**Comment by prasad-edlabadka** [comment]
IR doesn’t have temperature reading. IR blaster can only send signals. It can’t read anything from the AC.
