### ISSUE TITLE
Error displaying temperature data in HEAT mode.

### ISSUE THREAD

**Issue by YoYoZ** [prasad-edlabadka/homebridge-tuya-ir#19]
It is what it is. In all other modes it works fine, only in HEAT it shows null. Otherwise it operates as normal, and saves last set temperature in other mode. So, if you set 25 in AUTO, then switch to HEAT, it'll be 25 in HEAT.

My AC is Midea, if that matters.

![image](https://user-images.githubusercontent.com/1170548/134247391-919607f6-c02a-4b43-b81a-23e7f5d3fda4.png)
![image](https://user-images.githubusercontent.com/1170548/134247447-934c9fce-b4af-41a7-8660-4d25653be799.png)

**Comment by prasad-edlabadka** [comment]
New release should fix this.
