### ISSUE TITLE
The air conditioner cannot be controlled in heating mode.

### ISSUE THREAD

**Issue by idomenashko1** [prasad-edlabadka/homebridge-tuya-ir#22]
![CC912AB4-0661-458D-8254-E2AC66459C3E](https://user-images.githubusercontent.com/90921082/135716797-56324a83-f143-44e0-ace3-0fa55b84bd0c.png)
 Do not let the degrees change in heating mode.  In cooling mode works great

**Comment by idanmantin** [comment]
Hey, I have the same issue with the AC.
Only cool mode is working, but the Heat mode and Auto mode not working....(Can't adjust the degrees).

**Comment by prasad-edlabadka** [comment]
Have you tried with latest release? I don't have a heater so can't test it with real device.

**Comment by idanmantin** [comment]
It's still not working for me. Can't control my AC degree on Heating mode. 

'homebridge-tuya-ir v0.1.2'

**Comment by YoYoZ** [comment]
++, same issue. Only with heater. Assume that smth is wrong with temperature ranges in the plugin, getting out of bounds?

**Comment by idanmantin** [comment]
> Assuming no longer a problem with latest release. Closing. Please feel free to re-open

Still not working...
