### ISSUE TITLE
Help in finding IR blaster ID

### ISSUE THREAD

**Issue by sankalpdomore** [prasad-edlabadka/homebridge-tuya-ir#23]
Hi, my device is not showing up. 

I have added the IR Blaster Device ID the same from the Tuya IOT platform but the remote is still not showing up.

Is there something I am missing?

Screenshot of HomeBridge settings:
![CleanShot 2021-10-04 at 20 22 34@2x](https://user-images.githubusercontent.com/18334593/135873912-d6c5301e-0ab6-4b33-912e-96555b622677.png)

Screenshot of ID from Tuya IOT platform
![CleanShot 2021-10-04 at 20 22 59@2x](https://user-images.githubusercontent.com/18334593/135873954-1d9607f7-a458-445f-9b1b-acc206a256e9.png)

**Comment by sankalpdomore** [comment]
Let me try that. And the IR remote ID will be the same as IR Blaster Device ID?

**Comment by prasad-edlabadka** [comment]
The plug-in supports only fans and AC for now.

**Comment by duarch** [comment]
> Let me try that. And the IR remote ID will be the same as IR Blaster Device ID?

I have the same question. 

Its really confused, when I understand how it works I'm gonna do a tutorial.
By the way, why do you call "Blaster"? I didn't find the "Blaster" anywhere.

**Comment by duarch** [comment]
> So IR Blaster ID is the id of the Smart IR devices
> 
> and Remote Id are IDs are remotes you add to the Smart IR

Thank you, BUT where can I find these IDs of remotes I add. The only ID I found was the Smart IR it self. 
![image](https://user-images.githubusercontent.com/42032253/137588551-515fcf2c-b9b5-4622-ba27-0783b1054058.jpeg)
