### ISSUE TITLE
I think the name of the Tuya api service has changed.

### ISSUE THREAD

**Issue by MoonJuhan** [prasad-edlabadka/homebridge-tuya-ir#24]
I was reinstalling this plugins. There are a total of three api services that inform you to install from the README.

1. IR Control Hub Open Service
2. Smart Home Devices Management
3. Authorization

Among them, I searched for "Smart Home Devices Management" on the tuya platform, but I couldn't find it.
I think the name has changed to "Device Connection Service", so please check it.

**Comment by boogeymxn** [comment]
I cant find a api named "Device Connection Service" did they just change its name again?
