### ISSUE TITLE
Emptying Cache

### ISSUE THREAD

**Issue by jun6lee** [prasad-edlabadka/homebridge-tuya-ir#26]
I was testing what it does with the TV/Lights, but no longer need them.

Despite removing from json/config. They still seem to load from cache and show up in Homekit.
I could just hide them in Homekit but would like to know how to empty said cache.

**Comment by prasad-edlabadka** [comment]
That's homebridge caching the devices and not plugin. You can install [homebridge-ui-x](https://github.com/oznu/homebridge-config-ui-x) which allows you to clear homebridge cache.
