### ISSUE TITLE
Can't setup some devices

### ISSUE THREAD

**Issue by boogeymxn** [prasad-edlabadka/homebridge-tuya-ir#3]
I can't setup a wall fan with this plugin, however I've managed to setup my Air Conditioner. YES, I know currently Air Conditioner is the only device that is support with this plugin. But usually people like me uses other appliances like a fan, more often than a Air Conditioner. So could you add this to it? This is my kind advice

**Comment by prasad-edlabadka** [comment]
On my development list. Haven't been keeping well last week. Hope to work on this during this week.

**Comment by prasad-edlabadka** [comment]
Doesn't look like Tuya IR APIs support controlling FANs yet. Only AC, STB and TVs are supported.

**Comment by boogeymxn** [comment]
Oh no, that doesn’t sounds good. But I’m using it with the smart life app. Anyways, I have a tuya IOT developer account in which I have added this devices so If you need anything like the details of the device please feel free to let me know.

**Comment by boogeymxn** [comment]
hey one more thing, so does that mean we cant add a ir controlled fan to it??? however, in India we use fans more than ACs right...

**Comment by prasad-edlabadka** [comment]
I have reached out to Tuya support for help. Let's see what they come back with.

**Comment by madtempest** [comment]
> Doesn't look like Tuya IR APIs support controlling FANs yet. Only AC, STB and TVs are supported.

+1 for TVs if you can get it to work :)

**Comment by prasad-edlabadka** [comment]
Finally got fan working. Pushed a new version

**Comment by prasad-edlabadka** [comment]
> > Doesn't look like Tuya IR APIs support controlling FANs yet. Only AC, STB and TVs are supported.
> 
> +1 for TVs if you can get it to work :)

TV will be tracked in separate enhancement request
