### ISSUE TITLE
Configure AC parameters 

### ISSUE THREAD

**Issue by Colequi1** [prasad-edlabadka/homebridge-tuya-ir#32]
Hi! Thanks for the plug-in! 
im able to turn on and off and control de AC Mode, but can’t set specific temperature, is this posible through parameters specifications? Do you have an example config of this?
Thanks!!!

**Comment by prasad-edlabadka** [comment]
Is your device added as AC...if yes, temperature setting is handled by Home app. Can you please share more details if it's not working?

**Comment by Colequi1** [comment]
Hi I made it work a few days after.. 
but what I haven’t worked around yet is, I Have Smart iR controls with temperature and humidity, the HomeKit doesn’t read the device, but it does read the AC and the TV.. is there something different for those? I bought them in China, so I figure it might not be that common for it to be developed..
Thanks!!!

**Comment by prasad-edlabadka** [comment]
Humidifier are not supported for statuses.
