### ISSUE TITLE
Failed to change device status 

### ISSUE THREAD

**Issue by boogeymxn** [prasad-edlabadka/homebridge-tuya-ir#37]
"Failed to change device status due to error the infrared code corresponding to the key does not exist" getting this error in log when trying to make a command. it's a DIY wall fan remote

**Comment by boogeymxn** [comment]
Tried reinstalling the plugin and doing all the steps once again still the same problem...........

**Comment by prasad-edlabadka** [comment]
Which fan are you registering. Can you control us using Tuya app and not using HomeKit?

**Comment by boogeymxn** [comment]
Its fixed now! I don't know how but after few days it's started working. And yes it was working fine in the smart life app at the time of this issue.
