### ISSUE TITLE
Control the fan speed with two buttons

### ISSUE THREAD

**Issue by VCTGomes** [prasad-edlabadka/homebridge-tuya-ir#39]
My Fan works with two buttons to increase or decrease the speed (like the volume), so it ins't possible to control the speed using the HomeKit because it just recognize one button to control the speed.

Is it possible to change how it works manually to make the Homebridge-tuya-ir read the speed buttons from Tuya app?

![image](https://user-images.githubusercontent.com/2366600/153264201-5a5ee164-a6df-4501-836a-c13e34c6eda6.png)

**Comment by prasad-edlabadka** [comment]
Apple Home doesn't support up and down feature for fan speed. Thus, I have done a work around to change speed using fan speed control.
