### ISSUE TITLE
Lost function

### ISSUE THREAD

**Issue by Colequi1** [prasad-edlabadka/homebridge-tuya-ir#41]
Hi! I was operating great, with the cloud project and everything, then I had to restart the HB service a couple of timer due to other plug-in and now the log says this plug-in has access denied tried uninstalling and reinstalling but no luck.
Here is a copy of the log with the errors.
Any idea or solution? Pliss 
Been lovin the IoT
![7F7F4964-94F7-4F83-9507-8D9E5DA8C124](https://user-images.githubusercontent.com/93551654/153513323-c892e5f4-6a84-4aa3-8ec7-830e9d25eb7e.png)
![153E3550-6FAE-4FD4-AF9B-07C5B0191A3B](https://user-images.githubusercontent.com/93551654/153513347-793299b7-5141-4b73-9a8c-a84ae19f8a8b.png)

**Comment by prasad-edlabadka** [comment]
I have added good amount of error handling now. Can you please update and let me know if error persists? Please feel free to reopen if error persists.
