### ISSUE TITLE
Auto and Heat mods mixed up.

### ISSUE THREAD

**Issue by torukonami** [prasad-edlabadka/homebridge-tuya-ir#42]
When trying to turn on heat mode cannot select any temperature value but in auto mode I can select. So for heat I have to choose automode and for auto have to choose heat
![IMG_0861](https://user-images.githubusercontent.com/98821670/153614961-16db0c64-63ef-4020-ba8b-a576a32467ef.png)
![IMG_0862](https://user-images.githubusercontent.com/98821670/153614985-7a6e2e25-e8b4-4331-a9e2-dd6639b00d31.png)
.

**Comment by prasad-edlabadka** [comment]
Can you please provide logs and your config?

**Comment by gonzechevnublit** [comment]
I'm having this issue too...

**Comment by gonzechevnublit** [comment]
![image](https://user-images.githubusercontent.com/51458471/177212062-2008321c-5c05-48e1-9895-6aa7ef7a4954.png)

**Comment by prasad-edlabadka** [comment]
Can you please try using v1.0.0? It's released as beta so you will have to install it manually. It has some breaking changes. So, please backup your confit.json before installing

**Comment by gonzechevnublit** [comment]
I added this code for heating:

`this.service.getCharacteristic(this.platform.Characteristic.HeatingThresholdTemperature)
            .onGet(this.getCoolingThresholdTemperatureCharacteristic.bind(this))
            .onSet(this.setCoolingThresholdTemperatureCharacteristic.bind(this))
            .setProps({
            unit: undefined,
            minValue: 17,
            maxValue: 30,
            minStep: 1,
        })`

**Comment by prasad-edlabadka** [comment]
Fixed in #56
