### ISSUE TITLE
DIY Devices

### ISSUE THREAD

**Issue by louis49** [prasad-edlabadka/homebridge-tuya-ir#43]
Hello, 
I would like to be able to control my extractor hood with several functions (Turn hood on/off, light on/off) and "clone" the IR commands sent by the remote control supplied with the device.
In the README, you mention: "All other Pre-configured remotes will be added as switch to turn them on and off only. No other feature. (No DIY devices)": is this the case you are talking about ?
I haven't bought this Tuya product yet, but I want to know if from your experience, you know if it is possible that my idea can be realized (natively with your repo, or with a dedicated code).
Thanks in advance for your feedback

**Comment by prasad-edlabadka** [comment]
If your controller works on IR, you can configure it using Tuya IR learning mode. This allows you to create DIY device with each button on your remote. However, you will need to map it homebridge which will require adding a device type. If you can, feel free to fork and create a PR to enhance the plug-in.

**Comment by louis49** [comment]
Thank you a lot for these quick answer ! I order https://www.amazon.fr/dp/B08XC3X4H7/

**Comment by prasad-edlabadka** [comment]
👍
