### ISSUE TITLE
Home app issues when Plugin is enabled

### ISSUE THREAD

**Issue by rkhirata** [prasad-edlabadka/homebridge-tuya-ir#44]
First, many thanks for writing and dedicating your time to this plugin.

Now, for the issue: after configuring, I can control the IR blaster (S08 Pro) withinh the HomeBridge page (along with all other accessories on the webpage panel).

However, all accessories from HomeBridge are non responsive inside the iPhone Home App.

Within my setup, I have the Tuya Lan Plugin configured. Is this an issue?

If I disable the plugin (homebridge-tuya-ir) everything goes back to normal.

Thanks in advance!

![HB](https://user-images.githubusercontent.com/9965882/160119837-74dd2d76-fa14-4964-a3f5-161954e5b873.jpg)

![WhatsApp Image 2022-03-25 at 9 20 10 AM](https://user-images.githubusercontent.com/9965882/160119691-8e658a80-8be8-44d6-b88e-9274b4f2590e.jpeg)

![HB2](https://user-images.githubusercontent.com/9965882/160120081-d8edd9f2-ec6a-489b-b3db-9f2c33e26215.jpg)

**Comment by prasad-edlabadka** [comment]
Closing due to no response. please feel free to reopen if required.
