### ISSUE TITLE
Control Fan Speed

### ISSUE THREAD

**Issue by Rahulsharma0810** [prasad-edlabadka/homebridge-tuya-ir#48]
Ton thanks for making it.

Currently only Fan on/off working, when trying to increase or decrease speed logs shows 

```
[5/9/2022, 8:37:19 PM] [TuyaIR] Failed to invoke API param is illegal , please check it
[5/9/2022, 8:37:19 PM] [TuyaIR] Failed to get commands for the fan. Defaulting to standard values. These may not work.
[5/9/2022, 8:37:19 PM] [TuyaIR] Failed to change Fan speed due to an error the infrared code corresponding to the key does not exist
```

The Fan I am using has independent Speed control buttons, instead of the volume kind button to decrease/increase.

![IMG_1D4B8B2E7BB0-1](https://user-images.githubusercontent.com/9934859/167423637-5828d3ee-21e1-4b6c-9519-4d87ce8e77ab.jpeg)

Is there a way to use speed controls?

**Comment by louis49** [comment]
You can try to fork this repo and use the DIY device function that I pushed

**Comment by prasad-edlabadka** [comment]
> You can try to fork this repo and use the DIY device function that I pushed

This is already merged with main branch and available on npm. 

The changes for DIY will need to be extended for speed. I think current implementation support only ON and OFF for DIY.

**Comment by prasad-edlabadka** [comment]
One way to do this is define a custom remote in Tuya and learn each key on your remote one by one. Then use this custom remote's device Id. It won't show up as Fan but you will get all the buttons as switches.

**Comment by VCTGomes** [comment]
> You can try to fork this repo and use the DIY device function that I pushed

Good suggestion. I have a Fan with speed up and down. I think it isn't possible to create a workaround with using the slider control, right?

**Comment by prasad-edlabadka** [comment]
There is now DIY accessory for this
