### ISSUE TITLE
Deleting Cached Items

### ISSUE THREAD

**Issue by sodolocke** [prasad-edlabadka/homebridge-tuya-ir#52]
Is there a way to delete remotes that are no longer in the tuya cloud? Currently it pulls from the cache so old remotes are still there.

**Comment by sodolocke** [comment]
I uninstalled and reinstalled the plugin and got it to remove the cache, it would be nice to be able to flag a ir device to clear its child devices from cache

Love the plugin

**Comment by prasad-edlabadka** [comment]
Homebridge UI provides you option to remove accessories. But I will take it as a feature request to automatically remove remotes that are deleted from the config.

**Comment by prasad-edlabadka** [comment]
Fixed in v1.0.0. it's published as beta right now. Please let me know the feedback.
