### ISSUE TITLE
Avatto IR 

### ISSUE THREAD

**Issue by qattanson** [prasad-edlabadka/homebridge-tuya-ir#54]
I have the IR installed in tuya. I configured it in homebridge to control it (AC unit) from the HomeKit app in my iphone. It is showing on my iphone and in homebridge, however it is not controlling the IR (not switching the AC on and off). Please advise. 

 "name": "TuyaIR",
            "client_id": "xxxxxxxxxxxx",
            "secret": "xxxxxxxxxxx",
            "region": "eu",
            "smartIR": [
                {
                    "deviceId": "bf7b9xxxxxxxxxxxx",
                    "autoFetchRemotes": true,
                    "devices": [
                        {
                            "id": "bf7b9xxxxxxxxxxxxxx",
                            "diy": false,
                            "model": "S08",
                            "brand": "avatto"
                        }
                    ]
                }
            ],
            "platform": "TuyaIR"

**Comment by prasad-edlabadka** [comment]
Can you please send logs?

**Comment by qattanson** [comment]
![Tuya IR issue](https://user-images.githubusercontent.com/108429456/177801872-8b4954a6-6ab1-4bfc-ace8-1d89bec711d8.png)

**Comment by prasad-edlabadka** [comment]
Need more logs. This isn't showing any error as to what happened.

**Comment by qattanson** [comment]
It does not show any errors and the device is appearing in the homekit app as well as the homebridge local. It shows that you can switch it on and off and control the temperature, however does not work.

**Comment by qattanson** [comment]
All sorted.

I realized the mistake!!. I was using the Device ID of the assigned device instead of the IR remote itself.
I change it now and it is working perfectly.

Thank you so much!!
