### ISSUE TITLE
AC no longer works after the last update

### ISSUE THREAD

**Issue by andreizet66** [prasad-edlabadka/homebridge-tuya-ir#59]
After installing the update and restarting homebridge, the plugin is no longer able to control the AC. Shortly after, the AC disappears from Homekit. I wanted to save the logs, but Homebridge showed an error in config.json and restarted immediately. Had to revert to v1.0.1 to get everything working again.

**Comment by andreizet66** [comment]
Managed to save logs this time. Homebridge web interface log returns:

> [7/14/2022, 12:05:08 PM] [TuyaIR] Client ID is not configured. Please check your config.json

Checkd config.json, Client ID is actually configured. Let me know how I can be of any further assistence.

**Comment by alszaitsev** [comment]
I think i've managed to resolve the case. Swithed tuya ir (v.1.0.3) to Child bridge mode. Turned on auto fetching. restarted child process several times. Then added TuyaIR as a bridge in HomeKit and added devices to rooms. Now do not breath)

**Comment by zixuan96** [comment]
I refilled the Client ID and Client Secret after updating, and it works now.

**Comment by prasad-edlabadka** [comment]
Great. Closing the issue then.
