### ISSUE TITLE
problem with ir remote 

### ISSUE THREAD

**Issue by hashmaker1982** [prasad-edlabadka/homebridge-tuya-ir#63]
hi , I have update the plugin to last and now i just control ac remote , not tv not diy  , and the homebridge log say when i click on some remote [14/7/2022, 19:19:17] [TuyaIR] Failed to change device status due to error raw_key can not be null . if i come back to older version of the plugin , not work too. Please help

**Comment by hashmaker1982** [comment]
ok , for me the version 0.2.1 working with all other remote , so i cannot update the plugin until solve this issue, thanks

**Comment by prasad-edlabadka** [comment]
Fixed in version v1.0.5. Please check and let me know.
