### ISSUE TITLE
Region

### ISSUE THREAD

**Issue by sirdir1972** [prasad-edlabadka/homebridge-tuya-ir#67]
My devices are placed into 'central europe' region (although I'm in western Europe). This can't be chosen from the config UI and I don't know what's the correct shortcut, if it even is defined in the project…

**Comment by sythesigh** [comment]
> My devices are placed into 'central europe' region (although I'm in western Europe). This can't be chosen from the config UI and I don't know what's the correct shortcut, if it even is defined in the project…

Mine worked with just Europe, if that’s any help?

**Comment by sirdir1972** [comment]
> Mine worked with just Europe, if that’s any help?

Correct, in the end it has been another issue. Now I'm having another problem but don't even know how to report it :) I'll see.

**Comment by prasad-edlabadka** [comment]
Europe should work. There are some critical fixes in v1.0.5. Please test and let me know.
