### ISSUE TITLE
Fan issue

### ISSUE THREAD

**Issue by NewUser14** [prasad-edlabadka/homebridge-tuya-ir#71]
Hi. 
I can’t find pre configured fan that is working with my fan perfectly, 
So I created diy remote . The separated buttons are annoying , so I created a dummy pre configured fan button and with HomeKit automation I made rules to press the on off buttons, to make it look good with one button only. And it works well. 

The last problem that Is occurring is that after a while, when I’m going to HomeKit app, it’s refreshing the status of the buttons , and it’s turning off the dummy fan and then pressing the off button by itself. 
any ideas?

**Comment by prasad-edlabadka** [comment]
You can create a DIY Fan in Tuya App. Pick any brand and then learn each key from the remote. Add this device Id to the plugin and set the DIY flag to true. That would give you a standard fan in HomeKit without having to put any automation.
