### ISSUE TITLE
Wrong temp range in homekit

### ISSUE THREAD

**Issue by xazzy61** [prasad-edlabadka/homebridge-tuya-ir#74]
Hello,

The plugin works very well, but when the AC Fujitsu General is exposed to homekit there is some mods - auto, heat, cool and etc. but in heat mode max temp is only 25C(range is from 10 to 25, my ac support from 18 to 30), in cool mode there is range from 10 to 30. How this can be adjusted to match my ranges? In the tuya app the ranges are correct - from 18 to 30.

**Comment by prasad-edlabadka** [comment]
Fixed in v1.0.7.
