### ISSUE TITLE
Many things not working 

### ISSUE THREAD

**Issue by Magna66** [prasad-edlabadka/homebridge-tuya-ir#76]
[TuyaIR] Failed to change Fan status due to error categoryId
[TuyaIR] Failed to change device status due to error categoryId

Back to version 1.0.6, and please no need to update unless it works. Thank you.

**Comment by prasad-edlabadka** [comment]
Fixed. Tuya API changed in the background had to update.

**Comment by Magna66** [comment]
Thank you so much, everything working fine.
