### ISSUE TITLE
Need for a paid subscription

### ISSUE THREAD

**Issue by missflash** [prasad-edlabadka/homebridge-tuya-ir#79]
Thanks for the great plugin. :-)
It works great except for some minor issues.

1) In order to finish Tuya Authorization, I have to activate trial subscription for "IR Control Hub Open Service" API.
After expiration of that API, should I pay for that?

2) Also I couldn't find "Device Connection Service", "Authorization" API at the Tuya platform.
I think you need to update your [README.md](https://github.com/prasad-edlabadka/homebridge-tuya-ir#readme) description.

Thank you

**Comment by prasad-edlabadka** [comment]
Thanks. Will update in next version. I haven't paid anything so far (fingers crossed).
