### ISSUE TITLE
Too many logs

### ISSUE THREAD

**Issue by 1HyperZ** [prasad-edlabadka/homebridge-tuya-ir#80]
Hi if it is possible to make the plug-in send less log messages it will be better it just shows refresh and need to refresh not really helping to debug things![image](https://user-images.githubusercontent.com/77121655/190728561-1829b8d8-95bb-4a99-a041-1a2b44bc35de.png)

**Comment by prasad-edlabadka** [comment]
These are all debug logs and printed only when you set your homebridge in debug mode. You can change the level to Info as per homebridge documentation.

**Comment by 1HyperZ** [comment]
I'm not on debug mode

**Comment by 1HyperZ** [comment]
![image](https://user-images.githubusercontent.com/77121655/190928996-a95f6ef6-8967-4bd9-b190-d3d7700ce419.jpeg)

**Comment by prasad-edlabadka** [comment]
Reduced logs in v1.0.9 at info level

**Comment by 1HyperZ** [comment]
Ok thanks will try it
