### ISSUE TITLE
(Request) Blackout Blinds

### ISSUE THREAD

**Issue by JanMayron** [prasad-edlabadka/homebridge-tuya-ir#86]
Awesome plug-in in! (Only one to be working for my desired outcome which is to control AC, Ceiling Fans, and blackout/shutter blinds all from MoesGo Universal controller per room).

Currently only have added AC. Working perfectly fine should I mention. However, trying to add my blinds, they only appear as switches and not working at all to pull blinds up and down.

I would highly appreciate someone adding some code to the plug-in, in order to enhance it for blinds. A simple up-down and pause will do. 

Thanks!!

**Comment by prasad-edlabadka** [comment]
Unfortunately, Tuya doesn't support blinds yet on IR control. So, there is no way to setup the remote other than doing DIY. You can always do it as DIY remote which already exists as a feature.
