### ISSUE TITLE
'error token invalid' about weekly

### ISSUE THREAD

**Issue by tumispro** [prasad-edlabadka/homebridge-tuya-ir#90]
About every week I have to restart my homebridge server due to a 'error token invalid' error from Tuya, causing my Tuya devices to stop working. Is there any workaround known perhaps?

<img width="927" alt="Screenshot 2022-11-10 at 15 56 30" src="https://user-images.githubusercontent.com/1461426/201124904-27e26d68-123b-4d30-8462-46e85b648017.png">

**Comment by prasad-edlabadka** [comment]
I will look into it.

**Comment by bass63** [comment]
I have the same issue. Reboot fixes it

**Comment by prasad-edlabadka** [comment]
I couldn't find anything wrong as my server has been running perfectly fine. I am closing the issue. Please feel free to reopen with more logs.
