### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by 0x5e** [prasad-edlabadka/homebridge-tuya-ir#91]
Hello @prasad-edlabadka ,
I am the former Tuya employee who propose to launch the official tuya plugin project. Now since the official plugin is not active anymore, I am maintaining a fork version with brunch of bug fix and new device support. In the next minor version I plan to add IR device support, and I found your project. Since we are both using Tuya OpenAPI, would you like to join with me together? You can focusing on the IR part and I will forcus on the base part of the API/MQTT/user/home/device and so on.

**Comment by prasad-edlabadka** [comment]
Hello,

Can you please send the link to your plugin? Also, I guess integrating "regular" Tuya devices with IR control is tricky because of the way Tuya structures the devices and APIs. e.g. there isn't any option to operate devices offline / lan mode.

**Comment by 0x5e** [comment]
Thanks for the reply. here's the plugin: https://github.com/0x5e/homebridge-tuya-platform
IR is already work in progress, and the lan mode is not supported, I wish I can find a legal way to support this.
