### ISSUE TITLE
RF Support?

### ISSUE THREAD

**Issue by aayushbhatia06** [prasad-edlabadka/homebridge-tuya-ir#95]
Last I checked this plugin did not support RF. I still use this for IR but was wondering if there is RF support added yet or planned?

Thanks

**Comment by prasad-edlabadka** [comment]
There isn't. This plugin is exclusively for Tuya IR.

**Comment by aayushbhatia06** [comment]
Bummer. Sorry to ask another stupid question but is there a way I can convert the on/off switch I have right now to a "button" since there is no point of a switch knowing that the input device state cant be read

**Comment by prasad-edlabadka** [comment]
There isn't such control in HomeKit. If you use home bridge plugin exclusively to control the device, it will remember the state correctly.
