### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by ilyHapple** [prasad-edlabadka/homebridge-tuya-ir#98]
no connected homebridge
@
![IMG_1895](https://github.com/prasad-edlabadka/homebridge-tuya-ir/assets/31878663/68f851ee-3d11-4bc3-8795-63215929f647)

**Comment by prasad-edlabadka** [comment]
Can you please share complete logs?

**Comment by prasad-edlabadka** [comment]
Closing in absence of any activity. Please feel free to reopen if still an issue.
