### ISSUE TITLE
Help with Tuya IoT Platform

### ISSUE THREAD

**Issue by hughfr4nc15** [prasad-edlabadka/homebridge-tuya-ir#99]
Hello,

My Tuya "Trial Subscription" is about to expire... how do you guys keep this active and the plugin working? DO I need to renew it somehow? I extended it once but can't seem to do it now... Do I need to?

![image](https://github.com/prasad-edlabadka/homebridge-tuya-ir/assets/16179664/aa239d0f-df79-488a-ac81-652dfa3522d9)

Thanks in advance.

**Comment by prasad-edlabadka** [comment]
You keep renewing.
